name: CI workflow

on:
  workflow_dispatch:
env:
  #SESSION_PATH: "C:/Temp/session.xml"
  AWR_PATH: "C:/AWR/"
  USERNAME: $ {{ vars.USERNAME }}
  PASSWORD: $ {{ secrets.PASSWORD }}
  COMPUTERNAME: $ {{ vars.COMPUTERNAME }}
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: display credentials
        run: |
           echo "Username: $USERNAME"
           echo "Password: $PASSWORD"

      
